### ISSUE TITLE
Library Packages

### ISSUE THREAD

**Issue by 0205Rahul** [sanjeebtiwary/E-Commerce-Product-Recommendation#4]
![WhatsApp Image 2023-05-01 at 21 11 37](https://user-images.githubusercontent.com/108475337/235480311-307d9d76-3f3c-4369-bb70-324d322d223c.jpg)

Forms linrary has been installed with email-validation through the command:
pip install email_validator

pip install forms is out of date. Removed from Python 3.10
https://python.readthedocs.io/en/v2.7.2/library/fl.html

**Comment by sanjeebtiwary** [comment]
done now all good
