### ISSUE TITLE
Model issue

### ISSUE THREAD

**Issue by 0205Rahul** [sanjeebtiwary/E-Commerce-Product-Recommendation#5]
Global declaration issue in code (list2) -- check at your end.
 Check your save.py and check for Email ( ). 
The Flaskfrom has some issues. Model packages have not been deployed accordingly.

class RegistrationForm(FlaskForm):
      7     username = StringField('Username',
      8                            validators=[DataRequired(), Length(min=2, max=20)])
      9     email = StringField('Email',
     10                         validators=[DataRequired(), Email()])

**Comment by sanjeebtiwary** [comment]
it completed
